// Code generated by protoc-gen-go.
// source: protobuf/mediaappsingnal.proto
// DO NOT EDIT!

/*
Package mediaappsingnal is a generated protocol buffer package.

It is generated from these files:
	protobuf/mediaappsingnal.proto

It has these top-level messages:
	MediaAppSignalMessage
	MediaSignalMessage
	MediaCallMessage
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MediaAppSignalMessage struct {
	XSignal          *MediaSignalMessage                     `protobuf:"bytes,1,opt,name=_signal" json:"_signal,omitempty"`
	XCall            *MediaCallMessage                       `protobuf:"bytes,2,opt,name=_call" json:"_call,omitempty"`
	XBase            *MediaAppSignalMessage_MediaMessageBase `protobuf:"bytes,3,opt,name=_base" json:"_base,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *MediaAppSignalMessage) Reset()                    { *m = MediaAppSignalMessage{} }
func (m *MediaAppSignalMessage) String() string            { return proto.CompactTextString(m) }
func (*MediaAppSignalMessage) ProtoMessage()               {}
func (*MediaAppSignalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MediaAppSignalMessage) GetXSignal() *MediaSignalMessage {
	if m != nil {
		return m.XSignal
	}
	return nil
}

func (m *MediaAppSignalMessage) GetXCall() *MediaCallMessage {
	if m != nil {
		return m.XCall
	}
	return nil
}

func (m *MediaAppSignalMessage) GetXBase() *MediaAppSignalMessage_MediaMessageBase {
	if m != nil {
		return m.XBase
	}
	return nil
}

type MediaAppSignalMessage_MediaMessageBase struct {
	XPacketId        *uint64 `protobuf:"varint,1,req,name=_packetId" json:"_packetId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaAppSignalMessage_MediaMessageBase) Reset() {
	*m = MediaAppSignalMessage_MediaMessageBase{}
}
func (m *MediaAppSignalMessage_MediaMessageBase) String() string { return proto.CompactTextString(m) }
func (*MediaAppSignalMessage_MediaMessageBase) ProtoMessage()    {}
func (*MediaAppSignalMessage_MediaMessageBase) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *MediaAppSignalMessage_MediaMessageBase) GetXPacketId() uint64 {
	if m != nil && m.XPacketId != nil {
		return *m.XPacketId
	}
	return 0
}

type MediaSignalMessage struct {
	XLogin           *MediaSignalMessage_Login             `protobuf:"bytes,1,opt,name=_login" json:"_login,omitempty"`
	XLogout          *MediaSignalMessage_Logout            `protobuf:"bytes,2,opt,name=_logout" json:"_logout,omitempty"`
	XStateChanged    *MediaSignalMessage_OnlineStateChange `protobuf:"bytes,3,opt,name=_stateChanged" json:"_stateChanged,omitempty"`
	XPing            *MediaSignalMessagePing               `protobuf:"bytes,4,opt,name=_ping" json:"_ping,omitempty"`
	XPong            *MediaSignalMessagePong               `protobuf:"bytes,5,opt,name=_pong" json:"_pong,omitempty"`
	XLoginResp       *MediaSignalMessage_LoginResp         `protobuf:"bytes,6,opt,name=_loginResp" json:"_loginResp,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *MediaSignalMessage) Reset()                    { *m = MediaSignalMessage{} }
func (m *MediaSignalMessage) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage) ProtoMessage()               {}
func (*MediaSignalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MediaSignalMessage) GetXLogin() *MediaSignalMessage_Login {
	if m != nil {
		return m.XLogin
	}
	return nil
}

func (m *MediaSignalMessage) GetXLogout() *MediaSignalMessage_Logout {
	if m != nil {
		return m.XLogout
	}
	return nil
}

func (m *MediaSignalMessage) GetXStateChanged() *MediaSignalMessage_OnlineStateChange {
	if m != nil {
		return m.XStateChanged
	}
	return nil
}

func (m *MediaSignalMessage) GetXPing() *MediaSignalMessagePing {
	if m != nil {
		return m.XPing
	}
	return nil
}

func (m *MediaSignalMessage) GetXPong() *MediaSignalMessagePong {
	if m != nil {
		return m.XPong
	}
	return nil
}

func (m *MediaSignalMessage) GetXLoginResp() *MediaSignalMessage_LoginResp {
	if m != nil {
		return m.XLoginResp
	}
	return nil
}

type MediaSignalMessage_Login struct {
	XUid             *string `protobuf:"bytes,1,req,name=_uid" json:"_uid,omitempty"`
	XPwd             *string `protobuf:"bytes,2,req,name=_pwd" json:"_pwd,omitempty"`
	XPortal          *string `protobuf:"bytes,3,req,name=_portal" json:"_portal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_Login) Reset()                    { *m = MediaSignalMessage_Login{} }
func (m *MediaSignalMessage_Login) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage_Login) ProtoMessage()               {}
func (*MediaSignalMessage_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *MediaSignalMessage_Login) GetXUid() string {
	if m != nil && m.XUid != nil {
		return *m.XUid
	}
	return ""
}

func (m *MediaSignalMessage_Login) GetXPwd() string {
	if m != nil && m.XPwd != nil {
		return *m.XPwd
	}
	return ""
}

func (m *MediaSignalMessage_Login) GetXPortal() string {
	if m != nil && m.XPortal != nil {
		return *m.XPortal
	}
	return ""
}

type MediaSignalMessage_LoginResp struct {
	XToken           *string `protobuf:"bytes,1,req,name=_token" json:"_token,omitempty"`
	XCode            *uint32 `protobuf:"varint,2,req,name=_code" json:"_code,omitempty"`
	XFailedReason    *string `protobuf:"bytes,3,req,name=_failed_reason" json:"_failed_reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_LoginResp) Reset()                    { *m = MediaSignalMessage_LoginResp{} }
func (m *MediaSignalMessage_LoginResp) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage_LoginResp) ProtoMessage()               {}
func (*MediaSignalMessage_LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *MediaSignalMessage_LoginResp) GetXToken() string {
	if m != nil && m.XToken != nil {
		return *m.XToken
	}
	return ""
}

func (m *MediaSignalMessage_LoginResp) GetXCode() uint32 {
	if m != nil && m.XCode != nil {
		return *m.XCode
	}
	return 0
}

func (m *MediaSignalMessage_LoginResp) GetXFailedReason() string {
	if m != nil && m.XFailedReason != nil {
		return *m.XFailedReason
	}
	return ""
}

type MediaSignalMessage_Logout struct {
	XUid             *string `protobuf:"bytes,1,opt,name=_uid" json:"_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_Logout) Reset()                    { *m = MediaSignalMessage_Logout{} }
func (m *MediaSignalMessage_Logout) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage_Logout) ProtoMessage()               {}
func (*MediaSignalMessage_Logout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

func (m *MediaSignalMessage_Logout) GetXUid() string {
	if m != nil && m.XUid != nil {
		return *m.XUid
	}
	return ""
}

type MediaSignalMessage_OnlineStateChange struct {
	XUid             *string `protobuf:"bytes,1,req,name=_uid" json:"_uid,omitempty"`
	XState           *uint32 `protobuf:"varint,2,req,name=_state" json:"_state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_OnlineStateChange) Reset()         { *m = MediaSignalMessage_OnlineStateChange{} }
func (m *MediaSignalMessage_OnlineStateChange) String() string { return proto.CompactTextString(m) }
func (*MediaSignalMessage_OnlineStateChange) ProtoMessage()    {}
func (*MediaSignalMessage_OnlineStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 3}
}

func (m *MediaSignalMessage_OnlineStateChange) GetXUid() string {
	if m != nil && m.XUid != nil {
		return *m.XUid
	}
	return ""
}

func (m *MediaSignalMessage_OnlineStateChange) GetXState() uint32 {
	if m != nil && m.XState != nil {
		return *m.XState
	}
	return 0
}

type MediaSignalMessagePing struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MediaSignalMessagePing) Reset()                    { *m = MediaSignalMessagePing{} }
func (m *MediaSignalMessagePing) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessagePing) ProtoMessage()               {}
func (*MediaSignalMessagePing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 4} }

type MediaSignalMessagePong struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MediaSignalMessagePong) Reset()                    { *m = MediaSignalMessagePong{} }
func (m *MediaSignalMessagePong) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessagePong) ProtoMessage()               {}
func (*MediaSignalMessagePong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 5} }

type MediaCallMessage struct {
	XBase            *MediaCallMessage_BaseMesssage  `protobuf:"bytes,1,req,name=_base" json:"_base,omitempty"`
	XCallInitiate    *MediaCallMessage_CallInitiate  `protobuf:"bytes,2,opt,name=_call_initiate" json:"_call_initiate,omitempty"`
	XCallAccept      *MediaCallMessage_CallAccept    `protobuf:"bytes,3,opt,name=_call_accept" json:"_call_accept,omitempty"`
	XCallTerminate   *MediaCallMessage_CallTerminate `protobuf:"bytes,4,opt,name=_call_terminate" json:"_call_terminate,omitempty"`
	XCallInvite      *MediaCallMessage_CallInvite    `protobuf:"bytes,5,opt,name=_call_invite" json:"_call_invite,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *MediaCallMessage) Reset()                    { *m = MediaCallMessage{} }
func (m *MediaCallMessage) String() string            { return proto.CompactTextString(m) }
func (*MediaCallMessage) ProtoMessage()               {}
func (*MediaCallMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MediaCallMessage) GetXBase() *MediaCallMessage_BaseMesssage {
	if m != nil {
		return m.XBase
	}
	return nil
}

func (m *MediaCallMessage) GetXCallInitiate() *MediaCallMessage_CallInitiate {
	if m != nil {
		return m.XCallInitiate
	}
	return nil
}

func (m *MediaCallMessage) GetXCallAccept() *MediaCallMessage_CallAccept {
	if m != nil {
		return m.XCallAccept
	}
	return nil
}

func (m *MediaCallMessage) GetXCallTerminate() *MediaCallMessage_CallTerminate {
	if m != nil {
		return m.XCallTerminate
	}
	return nil
}

func (m *MediaCallMessage) GetXCallInvite() *MediaCallMessage_CallInvite {
	if m != nil {
		return m.XCallInvite
	}
	return nil
}

type MediaCallMessage_BaseMesssage struct {
	XFrom            *string `protobuf:"bytes,1,req,name=_from" json:"_from,omitempty"`
	XTo              *string `protobuf:"bytes,2,req,name=_to" json:"_to,omitempty"`
	XPortal          *string `protobuf:"bytes,3,req,name=_portal" json:"_portal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_BaseMesssage) Reset()         { *m = MediaCallMessage_BaseMesssage{} }
func (m *MediaCallMessage_BaseMesssage) String() string { return proto.CompactTextString(m) }
func (*MediaCallMessage_BaseMesssage) ProtoMessage()    {}
func (*MediaCallMessage_BaseMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *MediaCallMessage_BaseMesssage) GetXFrom() string {
	if m != nil && m.XFrom != nil {
		return *m.XFrom
	}
	return ""
}

func (m *MediaCallMessage_BaseMesssage) GetXTo() string {
	if m != nil && m.XTo != nil {
		return *m.XTo
	}
	return ""
}

func (m *MediaCallMessage_BaseMesssage) GetXPortal() string {
	if m != nil && m.XPortal != nil {
		return *m.XPortal
	}
	return ""
}

type MediaCallMessage_CallInitiate struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XCaller          *string `protobuf:"bytes,2,req,name=_caller" json:"_caller,omitempty"`
	XMediaSession    *string `protobuf:"bytes,3,req,name=_media_session" json:"_media_session,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallInitiate) Reset()         { *m = MediaCallMessage_CallInitiate{} }
func (m *MediaCallMessage_CallInitiate) String() string { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallInitiate) ProtoMessage()    {}
func (*MediaCallMessage_CallInitiate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 1}
}

func (m *MediaCallMessage_CallInitiate) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallInitiate) GetXCaller() string {
	if m != nil && m.XCaller != nil {
		return *m.XCaller
	}
	return ""
}

func (m *MediaCallMessage_CallInitiate) GetXMediaSession() string {
	if m != nil && m.XMediaSession != nil {
		return *m.XMediaSession
	}
	return ""
}

type MediaCallMessage_CallAccept struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XCallee          *string `protobuf:"bytes,2,req,name=_callee" json:"_callee,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallAccept) Reset()                    { *m = MediaCallMessage_CallAccept{} }
func (m *MediaCallMessage_CallAccept) String() string            { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallAccept) ProtoMessage()               {}
func (*MediaCallMessage_CallAccept) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *MediaCallMessage_CallAccept) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallAccept) GetXCallee() string {
	if m != nil && m.XCallee != nil {
		return *m.XCallee
	}
	return ""
}

type MediaCallMessage_CallTerminate struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XReason          *uint32 `protobuf:"varint,2,req,name=_reason" json:"_reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallTerminate) Reset()         { *m = MediaCallMessage_CallTerminate{} }
func (m *MediaCallMessage_CallTerminate) String() string { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallTerminate) ProtoMessage()    {}
func (*MediaCallMessage_CallTerminate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 3}
}

func (m *MediaCallMessage_CallTerminate) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallTerminate) GetXReason() uint32 {
	if m != nil && m.XReason != nil {
		return *m.XReason
	}
	return 0
}

type MediaCallMessage_CallInvite struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XMediaSession    *string `protobuf:"bytes,2,req,name=_media_session" json:"_media_session,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallInvite) Reset()                    { *m = MediaCallMessage_CallInvite{} }
func (m *MediaCallMessage_CallInvite) String() string            { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallInvite) ProtoMessage()               {}
func (*MediaCallMessage_CallInvite) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 4} }

func (m *MediaCallMessage_CallInvite) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallInvite) GetXMediaSession() string {
	if m != nil && m.XMediaSession != nil {
		return *m.XMediaSession
	}
	return ""
}

func init() {
	proto.RegisterType((*MediaAppSignalMessage)(nil), "MediaAppSignalMessage")
	proto.RegisterType((*MediaAppSignalMessage_MediaMessageBase)(nil), "MediaAppSignalMessage.MediaMessageBase")
	proto.RegisterType((*MediaSignalMessage)(nil), "MediaSignalMessage")
	proto.RegisterType((*MediaSignalMessage_Login)(nil), "MediaSignalMessage.Login")
	proto.RegisterType((*MediaSignalMessage_LoginResp)(nil), "MediaSignalMessage.LoginResp")
	proto.RegisterType((*MediaSignalMessage_Logout)(nil), "MediaSignalMessage.Logout")
	proto.RegisterType((*MediaSignalMessage_OnlineStateChange)(nil), "MediaSignalMessage.OnlineStateChange")
	proto.RegisterType((*MediaSignalMessagePing)(nil), "MediaSignalMessage.ping")
	proto.RegisterType((*MediaSignalMessagePong)(nil), "MediaSignalMessage.pong")
	proto.RegisterType((*MediaCallMessage)(nil), "MediaCallMessage")
	proto.RegisterType((*MediaCallMessage_BaseMesssage)(nil), "MediaCallMessage.BaseMesssage")
	proto.RegisterType((*MediaCallMessage_CallInitiate)(nil), "MediaCallMessage.CallInitiate")
	proto.RegisterType((*MediaCallMessage_CallAccept)(nil), "MediaCallMessage.CallAccept")
	proto.RegisterType((*MediaCallMessage_CallTerminate)(nil), "MediaCallMessage.CallTerminate")
	proto.RegisterType((*MediaCallMessage_CallInvite)(nil), "MediaCallMessage.CallInvite")
}

func init() { proto.RegisterFile("protobuf/mediaappsingnal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x94, 0x6f, 0x6f, 0xd3, 0x30,
	0x10, 0xc6, 0xd5, 0x35, 0x2d, 0xea, 0xf5, 0xcf, 0xa8, 0x11, 0x53, 0x88, 0x60, 0x4c, 0x15, 0xd3,
	0x86, 0x10, 0x41, 0xab, 0x00, 0x21, 0xc1, 0x9b, 0x6d, 0x6f, 0xa8, 0xc4, 0x84, 0xc4, 0x78, 0x1f,
	0x79, 0x8d, 0x5b, 0xac, 0xa5, 0x8e, 0x95, 0xb8, 0xf0, 0x05, 0xf8, 0x58, 0x88, 0xcf, 0xc6, 0x9d,
	0xed, 0xb6, 0x0b, 0x4d, 0xf7, 0xaa, 0xf1, 0xf9, 0x77, 0xbe, 0xbb, 0xe7, 0x1e, 0x15, 0x0e, 0x75,
	0x91, 0x9b, 0xfc, 0x66, 0x39, 0x7b, 0xb3, 0x10, 0xa9, 0xe4, 0x5c, 0xeb, 0x52, 0xaa, 0xb9, 0xe2,
	0x59, 0x6c, 0x2f, 0x46, 0x7f, 0x1b, 0xf0, 0xf8, 0x8a, 0x6e, 0xce, 0xb5, 0xbe, 0x96, 0x74, 0x71,
	0x25, 0xca, 0x92, 0xcf, 0x05, 0x7b, 0x01, 0x0f, 0x92, 0xd2, 0x46, 0xc2, 0xc6, 0x51, 0xe3, 0xb4,
	0x3b, 0x7e, 0x14, 0x5b, 0xb0, 0x4a, 0x1d, 0x41, 0x2b, 0x99, 0xf2, 0x2c, 0x0b, 0xf7, 0x2c, 0x33,
	0x74, 0xcc, 0x25, 0x46, 0x56, 0xc4, 0x7b, 0x24, 0x6e, 0x78, 0x29, 0xc2, 0xa6, 0x25, 0x4e, 0xe2,
	0xda, 0x72, 0x2e, 0xea, 0x0f, 0x17, 0x88, 0x47, 0xc7, 0xf0, 0xf0, 0xff, 0x18, 0x1b, 0x42, 0x27,
	0xd1, 0x7c, 0x7a, 0x2b, 0xcc, 0x24, 0xc5, 0xae, 0xf6, 0x4e, 0x83, 0xd1, 0xef, 0x00, 0x58, 0x4d,
	0x5f, 0x2f, 0xa1, 0x9d, 0x64, 0xf9, 0x5c, 0x2a, 0xdf, 0xfc, 0x93, 0x9a, 0xe6, 0xe3, 0x2f, 0x04,
	0xb0, 0x57, 0x38, 0x28, 0xa2, 0xf9, 0xd2, 0xf8, 0x21, 0xa2, 0x1d, 0x2c, 0x12, 0xec, 0x13, 0xf4,
	0x93, 0xd2, 0x70, 0x23, 0x2e, 0x7f, 0x70, 0x35, 0x17, 0xa9, 0x9f, 0xea, 0xb8, 0x2e, 0xe5, 0xab,
	0xca, 0xa4, 0x12, 0xd7, 0x1b, 0x9a, 0x9d, 0xa0, 0x16, 0x1a, 0xf5, 0x0f, 0x03, 0x9b, 0x15, 0xd6,
	0x65, 0xd1, 0xbd, 0x03, 0x73, 0x04, 0x5b, 0xf7, 0x80, 0x78, 0xcf, 0xce, 0x00, 0xdc, 0x9c, 0xdf,
	0x44, 0xa9, 0xc3, 0xb6, 0xa5, 0x9f, 0xed, 0x9c, 0x95, 0xa0, 0xe8, 0x2d, 0xb4, 0xdc, 0xe0, 0x3d,
	0x08, 0x92, 0xa5, 0x74, 0x42, 0x76, 0xec, 0x49, 0xff, 0x4a, 0x51, 0x03, 0x3a, 0xed, 0xa3, 0x28,
	0x3a, 0x2f, 0x0c, 0x6e, 0xbf, 0x49, 0x81, 0xe8, 0x02, 0x3a, 0xeb, 0x27, 0xd8, 0x00, 0xd5, 0x35,
	0xf9, 0xad, 0x50, 0x3e, 0xb7, 0x4f, 0x2e, 0xc8, 0x53, 0x61, 0x93, 0xfb, 0xec, 0x00, 0x06, 0xc9,
	0x8c, 0xcb, 0x4c, 0xa4, 0x49, 0x21, 0x78, 0x99, 0x2b, 0xff, 0xc6, 0x01, 0xb4, 0xbd, 0x8c, 0x9b,
	0xd2, 0x0d, 0x8c, 0x9f, 0xc1, 0x70, 0x5b, 0xab, 0x6a, 0x77, 0x54, 0xd1, 0xea, 0xee, 0x4a, 0x44,
	0x6d, 0x08, 0x48, 0x28, 0xfb, 0x8b, 0x3a, 0x8c, 0xfe, 0x04, 0xde, 0x2e, 0x77, 0xad, 0xf7, 0x7a,
	0x65, 0x3d, 0x7a, 0xa3, 0x3b, 0x3e, 0xdc, 0x32, 0x67, 0x4c, 0xae, 0xa2, 0x6f, 0xef, 0xd4, 0x81,
	0xf5, 0x72, 0x22, 0x95, 0x34, 0xd2, 0xd5, 0x6a, 0xd4, 0xe7, 0xd1, 0xf7, 0xc4, 0x53, 0x6c, 0x0c,
	0x3d, 0x97, 0xc7, 0xa7, 0x53, 0xa1, 0x8d, 0xb7, 0xc4, 0xd3, 0xfa, 0xac, 0x73, 0xcb, 0xb0, 0x0f,
	0xb0, 0xef, 0x72, 0x8c, 0x28, 0x16, 0x52, 0x51, 0x31, 0xe7, 0x89, 0xe7, 0xf5, 0x69, 0xdf, 0x57,
	0xd8, 0xa6, 0x9a, 0x54, 0x3f, 0x25, 0xa6, 0xb5, 0xee, 0xab, 0x36, 0xb1, 0x4c, 0xf4, 0x11, 0x7a,
	0x95, 0x49, 0x69, 0x5f, 0xb3, 0x22, 0x5f, 0x78, 0x71, 0xbb, 0xd0, 0xc4, 0x75, 0xee, 0xda, 0xfc,
	0x67, 0xe8, 0x55, 0xc6, 0x25, 0x80, 0x1a, 0x58, 0xef, 0x66, 0x15, 0x10, 0x85, 0x7f, 0x82, 0xf6,
	0x6f, 0xff, 0x6e, 0x92, 0x12, 0x2b, 0xca, 0xf5, 0xfe, 0x63, 0x80, 0x3b, 0x12, 0xec, 0x7e, 0xc7,
	0x2d, 0x99, 0x7c, 0xd1, 0xaf, 0xce, 0x5e, 0x9b, 0xe2, 0x2d, 0xe6, 0x7c, 0xf1, 0xce, 0x95, 0x70,
	0x73, 0x6f, 0xf3, 0xdb, 0x9d, 0xd9, 0x4a, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xbe, 0x33,
	0x1f, 0x27, 0x05, 0x00, 0x00,
}
