// Code generated by protoc-gen-go.
// source: protobuf/mediaappsingnal.proto
// DO NOT EDIT!

/*
Package mediaappsingnal is a generated protocol buffer package.

It is generated from these files:
	protobuf/mediaappsingnal.proto

It has these top-level messages:
	MediaAppSignalMessage
	MediaSignalMessage
	MediaCallMessage
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MediaAppSignalMessage struct {
	XSignal          *MediaSignalMessage `protobuf:"bytes,1,opt,name=_signal" json:"_signal,omitempty"`
	XCall            *MediaCallMessage   `protobuf:"bytes,2,opt,name=_call" json:"_call,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MediaAppSignalMessage) Reset()                    { *m = MediaAppSignalMessage{} }
func (m *MediaAppSignalMessage) String() string            { return proto.CompactTextString(m) }
func (*MediaAppSignalMessage) ProtoMessage()               {}
func (*MediaAppSignalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MediaAppSignalMessage) GetXSignal() *MediaSignalMessage {
	if m != nil {
		return m.XSignal
	}
	return nil
}

func (m *MediaAppSignalMessage) GetXCall() *MediaCallMessage {
	if m != nil {
		return m.XCall
	}
	return nil
}

type MediaSignalMessage struct {
	XLogin           *MediaSignalMessage_Login             `protobuf:"bytes,1,opt,name=_login" json:"_login,omitempty"`
	XLogout          *MediaSignalMessage_Logout            `protobuf:"bytes,2,opt,name=_logout" json:"_logout,omitempty"`
	XStateChanged    *MediaSignalMessage_OnlineStateChange `protobuf:"bytes,3,opt,name=_stateChanged" json:"_stateChanged,omitempty"`
	XPing            *MediaSignalMessagePing               `protobuf:"bytes,4,opt,name=_ping" json:"_ping,omitempty"`
	XPong            *MediaSignalMessagePong               `protobuf:"bytes,5,opt,name=_pong" json:"_pong,omitempty"`
	XLoginResp       *MediaSignalMessage_LoginResp         `protobuf:"bytes,6,opt,name=_loginResp" json:"_loginResp,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *MediaSignalMessage) Reset()                    { *m = MediaSignalMessage{} }
func (m *MediaSignalMessage) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage) ProtoMessage()               {}
func (*MediaSignalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MediaSignalMessage) GetXLogin() *MediaSignalMessage_Login {
	if m != nil {
		return m.XLogin
	}
	return nil
}

func (m *MediaSignalMessage) GetXLogout() *MediaSignalMessage_Logout {
	if m != nil {
		return m.XLogout
	}
	return nil
}

func (m *MediaSignalMessage) GetXStateChanged() *MediaSignalMessage_OnlineStateChange {
	if m != nil {
		return m.XStateChanged
	}
	return nil
}

func (m *MediaSignalMessage) GetXPing() *MediaSignalMessagePing {
	if m != nil {
		return m.XPing
	}
	return nil
}

func (m *MediaSignalMessage) GetXPong() *MediaSignalMessagePong {
	if m != nil {
		return m.XPong
	}
	return nil
}

func (m *MediaSignalMessage) GetXLoginResp() *MediaSignalMessage_LoginResp {
	if m != nil {
		return m.XLoginResp
	}
	return nil
}

type MediaSignalMessage_Login struct {
	XUid             *string `protobuf:"bytes,1,req,name=_uid" json:"_uid,omitempty"`
	XPwd             *string `protobuf:"bytes,2,req,name=_pwd" json:"_pwd,omitempty"`
	XPortal          *string `protobuf:"bytes,3,req,name=_portal" json:"_portal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_Login) Reset()                    { *m = MediaSignalMessage_Login{} }
func (m *MediaSignalMessage_Login) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage_Login) ProtoMessage()               {}
func (*MediaSignalMessage_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *MediaSignalMessage_Login) GetXUid() string {
	if m != nil && m.XUid != nil {
		return *m.XUid
	}
	return ""
}

func (m *MediaSignalMessage_Login) GetXPwd() string {
	if m != nil && m.XPwd != nil {
		return *m.XPwd
	}
	return ""
}

func (m *MediaSignalMessage_Login) GetXPortal() string {
	if m != nil && m.XPortal != nil {
		return *m.XPortal
	}
	return ""
}

type MediaSignalMessage_LoginResp struct {
	XToken           *string `protobuf:"bytes,1,req,name=_token" json:"_token,omitempty"`
	XCode            *uint32 `protobuf:"varint,2,req,name=_code" json:"_code,omitempty"`
	XFailedReason    *string `protobuf:"bytes,3,req,name=_failed_reason" json:"_failed_reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_LoginResp) Reset()                    { *m = MediaSignalMessage_LoginResp{} }
func (m *MediaSignalMessage_LoginResp) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage_LoginResp) ProtoMessage()               {}
func (*MediaSignalMessage_LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *MediaSignalMessage_LoginResp) GetXToken() string {
	if m != nil && m.XToken != nil {
		return *m.XToken
	}
	return ""
}

func (m *MediaSignalMessage_LoginResp) GetXCode() uint32 {
	if m != nil && m.XCode != nil {
		return *m.XCode
	}
	return 0
}

func (m *MediaSignalMessage_LoginResp) GetXFailedReason() string {
	if m != nil && m.XFailedReason != nil {
		return *m.XFailedReason
	}
	return ""
}

type MediaSignalMessage_Logout struct {
	XUid             *string `protobuf:"bytes,1,opt,name=_uid" json:"_uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_Logout) Reset()                    { *m = MediaSignalMessage_Logout{} }
func (m *MediaSignalMessage_Logout) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessage_Logout) ProtoMessage()               {}
func (*MediaSignalMessage_Logout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

func (m *MediaSignalMessage_Logout) GetXUid() string {
	if m != nil && m.XUid != nil {
		return *m.XUid
	}
	return ""
}

type MediaSignalMessage_OnlineStateChange struct {
	XUid             *string `protobuf:"bytes,1,req,name=_uid" json:"_uid,omitempty"`
	XState           *uint32 `protobuf:"varint,2,req,name=_state" json:"_state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaSignalMessage_OnlineStateChange) Reset()         { *m = MediaSignalMessage_OnlineStateChange{} }
func (m *MediaSignalMessage_OnlineStateChange) String() string { return proto.CompactTextString(m) }
func (*MediaSignalMessage_OnlineStateChange) ProtoMessage()    {}
func (*MediaSignalMessage_OnlineStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 3}
}

func (m *MediaSignalMessage_OnlineStateChange) GetXUid() string {
	if m != nil && m.XUid != nil {
		return *m.XUid
	}
	return ""
}

func (m *MediaSignalMessage_OnlineStateChange) GetXState() uint32 {
	if m != nil && m.XState != nil {
		return *m.XState
	}
	return 0
}

type MediaSignalMessagePing struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MediaSignalMessagePing) Reset()                    { *m = MediaSignalMessagePing{} }
func (m *MediaSignalMessagePing) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessagePing) ProtoMessage()               {}
func (*MediaSignalMessagePing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 4} }

type MediaSignalMessagePong struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MediaSignalMessagePong) Reset()                    { *m = MediaSignalMessagePong{} }
func (m *MediaSignalMessagePong) String() string            { return proto.CompactTextString(m) }
func (*MediaSignalMessagePong) ProtoMessage()               {}
func (*MediaSignalMessagePong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 5} }

type MediaCallMessage struct {
	XBase            *MediaCallMessage_BaseMesssage  `protobuf:"bytes,1,req,name=_base" json:"_base,omitempty"`
	XCallInitiate    *MediaCallMessage_CallInitiate  `protobuf:"bytes,2,opt,name=_call_initiate" json:"_call_initiate,omitempty"`
	XCallAccept      *MediaCallMessage_CallAccept    `protobuf:"bytes,3,opt,name=_call_accept" json:"_call_accept,omitempty"`
	XCallTerminate   *MediaCallMessage_CallTerminate `protobuf:"bytes,4,opt,name=_call_terminate" json:"_call_terminate,omitempty"`
	XCallInvite      *MediaCallMessage_CallInvite    `protobuf:"bytes,5,opt,name=_call_invite" json:"_call_invite,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *MediaCallMessage) Reset()                    { *m = MediaCallMessage{} }
func (m *MediaCallMessage) String() string            { return proto.CompactTextString(m) }
func (*MediaCallMessage) ProtoMessage()               {}
func (*MediaCallMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MediaCallMessage) GetXBase() *MediaCallMessage_BaseMesssage {
	if m != nil {
		return m.XBase
	}
	return nil
}

func (m *MediaCallMessage) GetXCallInitiate() *MediaCallMessage_CallInitiate {
	if m != nil {
		return m.XCallInitiate
	}
	return nil
}

func (m *MediaCallMessage) GetXCallAccept() *MediaCallMessage_CallAccept {
	if m != nil {
		return m.XCallAccept
	}
	return nil
}

func (m *MediaCallMessage) GetXCallTerminate() *MediaCallMessage_CallTerminate {
	if m != nil {
		return m.XCallTerminate
	}
	return nil
}

func (m *MediaCallMessage) GetXCallInvite() *MediaCallMessage_CallInvite {
	if m != nil {
		return m.XCallInvite
	}
	return nil
}

type MediaCallMessage_BaseMesssage struct {
	XFrom            *string `protobuf:"bytes,1,req,name=_from" json:"_from,omitempty"`
	XTo              *string `protobuf:"bytes,2,req,name=_to" json:"_to,omitempty"`
	XPortal          *string `protobuf:"bytes,3,req,name=_portal" json:"_portal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_BaseMesssage) Reset()         { *m = MediaCallMessage_BaseMesssage{} }
func (m *MediaCallMessage_BaseMesssage) String() string { return proto.CompactTextString(m) }
func (*MediaCallMessage_BaseMesssage) ProtoMessage()    {}
func (*MediaCallMessage_BaseMesssage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *MediaCallMessage_BaseMesssage) GetXFrom() string {
	if m != nil && m.XFrom != nil {
		return *m.XFrom
	}
	return ""
}

func (m *MediaCallMessage_BaseMesssage) GetXTo() string {
	if m != nil && m.XTo != nil {
		return *m.XTo
	}
	return ""
}

func (m *MediaCallMessage_BaseMesssage) GetXPortal() string {
	if m != nil && m.XPortal != nil {
		return *m.XPortal
	}
	return ""
}

type MediaCallMessage_CallInitiate struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XCaller          *string `protobuf:"bytes,2,req,name=_caller" json:"_caller,omitempty"`
	XMediaSession    *string `protobuf:"bytes,3,req,name=_media_session" json:"_media_session,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallInitiate) Reset()         { *m = MediaCallMessage_CallInitiate{} }
func (m *MediaCallMessage_CallInitiate) String() string { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallInitiate) ProtoMessage()    {}
func (*MediaCallMessage_CallInitiate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 1}
}

func (m *MediaCallMessage_CallInitiate) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallInitiate) GetXCaller() string {
	if m != nil && m.XCaller != nil {
		return *m.XCaller
	}
	return ""
}

func (m *MediaCallMessage_CallInitiate) GetXMediaSession() string {
	if m != nil && m.XMediaSession != nil {
		return *m.XMediaSession
	}
	return ""
}

type MediaCallMessage_CallAccept struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XCallee          *string `protobuf:"bytes,2,req,name=_callee" json:"_callee,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallAccept) Reset()                    { *m = MediaCallMessage_CallAccept{} }
func (m *MediaCallMessage_CallAccept) String() string            { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallAccept) ProtoMessage()               {}
func (*MediaCallMessage_CallAccept) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *MediaCallMessage_CallAccept) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallAccept) GetXCallee() string {
	if m != nil && m.XCallee != nil {
		return *m.XCallee
	}
	return ""
}

type MediaCallMessage_CallTerminate struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XReason          *uint32 `protobuf:"varint,2,req,name=_reason" json:"_reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallTerminate) Reset()         { *m = MediaCallMessage_CallTerminate{} }
func (m *MediaCallMessage_CallTerminate) String() string { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallTerminate) ProtoMessage()    {}
func (*MediaCallMessage_CallTerminate) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 3}
}

func (m *MediaCallMessage_CallTerminate) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallTerminate) GetXReason() uint32 {
	if m != nil && m.XReason != nil {
		return *m.XReason
	}
	return 0
}

type MediaCallMessage_CallInvite struct {
	XCallid          *string `protobuf:"bytes,1,req,name=_callid" json:"_callid,omitempty"`
	XMediaSession    *string `protobuf:"bytes,2,req,name=_media_session" json:"_media_session,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MediaCallMessage_CallInvite) Reset()                    { *m = MediaCallMessage_CallInvite{} }
func (m *MediaCallMessage_CallInvite) String() string            { return proto.CompactTextString(m) }
func (*MediaCallMessage_CallInvite) ProtoMessage()               {}
func (*MediaCallMessage_CallInvite) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 4} }

func (m *MediaCallMessage_CallInvite) GetXCallid() string {
	if m != nil && m.XCallid != nil {
		return *m.XCallid
	}
	return ""
}

func (m *MediaCallMessage_CallInvite) GetXMediaSession() string {
	if m != nil && m.XMediaSession != nil {
		return *m.XMediaSession
	}
	return ""
}

func init() {
	proto.RegisterType((*MediaAppSignalMessage)(nil), "MediaAppSignalMessage")
	proto.RegisterType((*MediaSignalMessage)(nil), "MediaSignalMessage")
	proto.RegisterType((*MediaSignalMessage_Login)(nil), "MediaSignalMessage.Login")
	proto.RegisterType((*MediaSignalMessage_LoginResp)(nil), "MediaSignalMessage.LoginResp")
	proto.RegisterType((*MediaSignalMessage_Logout)(nil), "MediaSignalMessage.Logout")
	proto.RegisterType((*MediaSignalMessage_OnlineStateChange)(nil), "MediaSignalMessage.OnlineStateChange")
	proto.RegisterType((*MediaSignalMessagePing)(nil), "MediaSignalMessage.ping")
	proto.RegisterType((*MediaSignalMessagePong)(nil), "MediaSignalMessage.pong")
	proto.RegisterType((*MediaCallMessage)(nil), "MediaCallMessage")
	proto.RegisterType((*MediaCallMessage_BaseMesssage)(nil), "MediaCallMessage.BaseMesssage")
	proto.RegisterType((*MediaCallMessage_CallInitiate)(nil), "MediaCallMessage.CallInitiate")
	proto.RegisterType((*MediaCallMessage_CallAccept)(nil), "MediaCallMessage.CallAccept")
	proto.RegisterType((*MediaCallMessage_CallTerminate)(nil), "MediaCallMessage.CallTerminate")
	proto.RegisterType((*MediaCallMessage_CallInvite)(nil), "MediaCallMessage.CallInvite")
}

func init() { proto.RegisterFile("protobuf/mediaappsingnal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x94, 0xdf, 0x6e, 0x13, 0x3b,
	0x10, 0xc6, 0x95, 0x66, 0x93, 0xa3, 0x4e, 0x92, 0xf6, 0xd4, 0x88, 0x6a, 0x59, 0x41, 0xa9, 0x22,
	0x10, 0x45, 0x88, 0x45, 0x8d, 0x00, 0x21, 0xc1, 0x4d, 0xdb, 0x1b, 0x2a, 0x51, 0x21, 0x51, 0xee,
	0x2d, 0x37, 0xeb, 0x04, 0x8b, 0x8d, 0x6d, 0xed, 0x3a, 0xf0, 0x02, 0x3c, 0x16, 0x0f, 0xc7, 0x8c,
	0xed, 0x26, 0x2c, 0xd9, 0xf4, 0xaa, 0xd9, 0xf1, 0xef, 0x9b, 0x3f, 0xdf, 0x8c, 0x0a, 0x47, 0xb6,
	0x32, 0xce, 0xdc, 0x2c, 0x67, 0xaf, 0x16, 0xb2, 0x50, 0x42, 0x58, 0x5b, 0x2b, 0x3d, 0xd7, 0xa2,
	0xcc, 0xfd, 0xc3, 0x98, 0xc3, 0xfd, 0x2b, 0x7a, 0x38, 0xb3, 0xf6, 0x5a, 0x51, 0xfc, 0x4a, 0xd6,
	0xb5, 0x98, 0x4b, 0xf6, 0x04, 0xfe, 0xe3, 0xb5, 0x8f, 0xa4, 0x9d, 0xe3, 0xce, 0xc9, 0x60, 0x72,
	0x2f, 0xf7, 0x60, 0x93, 0x3a, 0x86, 0x1e, 0x9f, 0x8a, 0xb2, 0x4c, 0x77, 0x3c, 0x73, 0x10, 0x98,
	0x0b, 0x8c, 0x44, 0x62, 0xfc, 0x2b, 0x01, 0xd6, 0x22, 0x7c, 0x0e, 0x7d, 0x5e, 0x9a, 0xb9, 0xd2,
	0x31, 0xfb, 0x83, 0x96, 0xec, 0xf9, 0x27, 0x02, 0xd8, 0x0b, 0xec, 0x04, 0x51, 0xb3, 0x74, 0xb1,
	0x4a, 0xb6, 0x85, 0x45, 0x82, 0x7d, 0x80, 0x11, 0xaf, 0x9d, 0x70, 0xf2, 0xe2, 0x9b, 0xd0, 0x73,
	0x59, 0xa4, 0x5d, 0x2f, 0x79, 0xda, 0x26, 0xf9, 0xac, 0x4b, 0xa5, 0xe5, 0xf5, 0x9a, 0x66, 0xcf,
	0x70, 0x1c, 0x8b, 0xfe, 0xa4, 0x89, 0x57, 0xa5, 0x6d, 0x2a, 0x7a, 0x0f, 0xa0, 0x41, 0xb0, 0x77,
	0x07, 0x88, 0xef, 0xec, 0x14, 0x20, 0xcc, 0xf9, 0x45, 0xd6, 0x36, 0xed, 0x7b, 0xfa, 0xd1, 0xd6,
	0x59, 0x09, 0xca, 0x5e, 0x43, 0x2f, 0x0c, 0x3e, 0x84, 0x84, 0x2f, 0x55, 0x81, 0x0e, 0xed, 0x9c,
	0xec, 0xfa, 0x2f, 0xfb, 0xb3, 0x40, 0x0f, 0xe8, 0x6b, 0x1f, 0x4d, 0xb1, 0xa6, 0x72, 0xb8, 0x9e,
	0x2e, 0x05, 0xb2, 0x73, 0xd8, 0x5d, 0xa5, 0x60, 0x7b, 0xe8, 0xae, 0x33, 0xdf, 0xa5, 0x8e, 0xda,
	0x11, 0xad, 0xc9, 0x14, 0xd2, 0x8b, 0x47, 0xec, 0x10, 0xf6, 0xf8, 0x4c, 0xa8, 0x52, 0x16, 0xbc,
	0x92, 0xa2, 0x36, 0x3a, 0xe6, 0x38, 0x84, 0x7e, 0xb4, 0x71, 0x5d, 0xba, 0x83, 0xf1, 0x53, 0x38,
	0xd8, 0xf4, 0xaa, 0xd9, 0x1d, 0x55, 0xf4, 0xbe, 0x87, 0x12, 0x59, 0x1f, 0x12, 0x32, 0xca, 0xff,
	0x45, 0x1f, 0xc6, 0xbf, 0x13, 0xf8, 0xff, 0xdf, 0xdb, 0x60, 0x2f, 0xb1, 0xad, 0x1b, 0x51, 0x4b,
	0x9f, 0x63, 0x30, 0x39, 0xda, 0xb8, 0x9e, 0xfc, 0x1c, 0x5f, 0xe9, 0xb7, 0xc7, 0xdf, 0x62, 0xdb,
	0x74, 0x6c, 0x5c, 0x69, 0xe5, 0x54, 0xa8, 0xd5, 0x69, 0xd7, 0xd1, 0xef, 0xcb, 0x48, 0xb1, 0x09,
	0x0c, 0x83, 0x4e, 0x4c, 0xa7, 0xd2, 0xba, 0x78, 0x12, 0x0f, 0xdb, 0x55, 0x67, 0x9e, 0x61, 0xef,
	0x60, 0x3f, 0x68, 0x9c, 0xac, 0x16, 0x4a, 0x53, 0xb1, 0x70, 0x13, 0x8f, 0xdb, 0x65, 0x5f, 0x6f,
	0xb1, 0x75, 0x35, 0xa5, 0x7f, 0x28, 0x94, 0xf5, 0xee, 0xaa, 0x76, 0xe9, 0x99, 0xec, 0x3d, 0x0c,
	0x1b, 0x93, 0xd2, 0xbe, 0x66, 0x95, 0x59, 0x44, 0x73, 0x07, 0xd0, 0xc5, 0x75, 0x6e, 0xdb, 0xfc,
	0x47, 0x18, 0x36, 0xc6, 0x25, 0x80, 0x1a, 0x58, 0xed, 0xe6, 0x36, 0x20, 0xab, 0x98, 0x82, 0xf6,
	0xef, 0xff, 0x1d, 0xf0, 0x1a, 0x2b, 0xaa, 0xd5, 0xfe, 0x73, 0x80, 0xbf, 0x2c, 0xd8, 0x9e, 0x27,
	0x2c, 0x99, 0xee, 0x62, 0xd4, 0x9c, 0xbd, 0x55, 0x12, 0x4f, 0x2c, 0xdc, 0xc5, 0x9b, 0x50, 0x22,
	0xcc, 0xbd, 0xc9, 0x6f, 0x76, 0xe6, 0x2b, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x19, 0x5d,
	0x04, 0xc7, 0x04, 0x00, 0x00,
}
